server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root+123
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    shutdown:
      enabled: false


teamplus:
  flag: 1  # 0:-> Off, 1:-> On
  name: teamPlus
  url: https://eim.gtcloud.net.tw/API/SuperHubService.ashx?ask=
  ask: broadcastMessage
  ch_sn: 14
  key: 525950c817004f569204b90ba8dc250a
  type: 1

xsms:
  flag: 0  # 0:-> Off, 1:->On
  name: SMS
  url: http://xsms.aptg.com.tw/XSMSAP/api/APIRTFastHttpRequest
  mdn: 0906180640
  uid: bb_test
  pwd: 123456
  call: 0906180640

mail:
  host: smtp.gmail.com
  port: 587
  authEnabled: true
  starttlsEnabled: true
  userAdress: aptg.alert@gmail.com
  userPwd: aptgalert123
  useDisplayname: Notification Mail
